// ==================== INFO ====================
var INFO = {
    name: "陈文亮",
    name_en: "Wenliang Chen",
    name_ja: "陳文亮",
    name_ko: "천원량",
    name_ar: "تشن ونليانغ",
    name_de: "Wenliang Chen",
    name_fr: "Wenliang Chen",
    hero_title: "设计师，也是运动者",
    hero_title_en: "Designer & Athlete",
    hero_title_ja: "デザイナー、そしてアスリート",
    hero_title_ko: "디자이너, 그리고 운동가",
    hero_title_ar: "مصمم ورياضي",
    hero_title_de: "Designer & Sportler",
    hero_title_fr: "Designer & Athlète",
    tagline: "广州美术学院 · 汽车设计方向。用东方美学做设计，用运动塑造身心。",
    tagline_en: "GAFA · Automotive Design. Eastern aesthetics in design, fitness in life.",
    tagline_ja: "広州美術学院 · 自動車デザイン専攻。東洋美学でデザインし、運動で心身を鍛える。",
    tagline_ko: "광저우미술학원 · 자동차디자인 전공. 동양미학으로 디자인하고, 운동으로 심신을 단련합니다.",
    tagline_ar: "أكاديمية غوانجو للفنون الجميلة · تصميم السيارات. الجماليات الشرقية في التصميم، واللياقة في الحياة.",
    tagline_de: "GAFA · Fahrzeugdesign. Östliche Ästhetik im Design, Fitness im Leben.",
    tagline_fr: "GAFA · Design Automobile. Esthétique orientale dans le design, fitness dans la vie.",
    meta_line1: "基于",
    meta_line1_en: "Based in ",
    meta_line1_ja: "拠点：",
    meta_line1_ko: "거주지: ",
    meta_line1_ar: "مقيم في ",
    meta_line1_de: "Ansässig in ",
    meta_line1_fr: "Basé à ",
    meta_city: "广州",
    meta_city_en: "Guangzhou",
    meta_city_ja: "広州",
    meta_city_ko: "광저우",
    meta_city_ar: "غوانزو",
    meta_city_de: "Guangzhou",
    meta_city_fr: "Guangzhou",
    meta_line2: "专注于",
    meta_line2_en: "Focus on ",
    meta_line2_ja: "専門：",
    meta_line2_ko: "전공: ",
    meta_line2_ar: "التخصص ",
    meta_line2_de: "Schwerpunkt ",
    meta_line2_fr: "Spécialisé en ",
    meta_focus: "汽车设计 × 健身",
    meta_focus_en: "Auto Design × Fitness",
    meta_focus_ja: "自動車デザイン × フィットネス",
    meta_focus_ko: "자동차디자인 × 피트니스",
    meta_focus_ar: "تصميم السيارات × اللياقة",
    meta_focus_de: "Fahrzeugdesign × Fitness",
    meta_focus_fr: "Design Auto × Fitness",
    meta_line3: "可用",
    meta_line3_en: "Available for ",
    meta_line3_ja: "対応可能：",
    meta_line3_ko: "가능: ",
    meta_line3_ar: "متاح لـ ",
    meta_line3_de: "Verfügbar für ",
    meta_line3_fr: "Disponible pour ",
    meta_avail: "合作与邀约",
    meta_avail_en: "Collaboration",
    meta_avail_ja: "コラボ・依頼",
    meta_avail_ko: "콜라보레이션",
    meta_avail_ar: "التعاون",
    meta_avail_de: "Zusammenarbeit",
    meta_avail_fr: "Collaboration",
    school: "广州美术学院 · 工业设计 · 汽车设计方向",
    school_en: "GAFA · Industrial Design · Automotive",
    school_ja: "広州美術学院 · 工業デザイン · 自動車デザイン専攻",
    school_ko: "광저우미술학원 · 공업디자인 · 자동차디자인 전공",
    school_ar: "أكاديمية غوانجو للفنون الجميلة · التصميم الصناعي · السيارات",
    school_de: "GAFA · Industriedesign · Fahrzeugdesign",
    school_fr: "GAFA · Design Industriel · Automobile",
    focus: "汽车设计 / 服务设计 / 数字建模",
    focus_en: "Auto Design / Service Design / Digital Modeling",
    focus_ja: "自動車デザイン / サービスデザイン / デジタルモデリング",
    focus_ko: "자동차디자인 / 서비스디자인 / 디지털모델링",
    focus_ar: "تصميم السيارات / تصميم الخدمات / النمذجة الرقمية",
    focus_de: "Fahrzeugdesign / Servicedesign / Digitale Modellierung",
    focus_fr: "Design Auto / Design de Service / Modélisation Numérique",
    design_lang: "东方意境，结构叙事",
    design_lang_en: "Eastern Mood, Structural Narrative",
    design_lang_ja: "東洋の意境、構造の物語",
    design_lang_ko: "동양의 의경, 구조의 서사",
    design_lang_ar: "الأجواء الشرقية، السرد الهيكلي",
    design_lang_de: "Östliche Stimmung, Strukturelle Erzählung",
    design_lang_fr: "Atmosphère Orientale, Narration Structurelle",
    design_lang_sub: "将文化意象转化为可感知的形态语言",
    design_lang_sub_en: "Transforming cultural imagery into perceivable form language",
    design_lang_sub_ja: "文化イメージを知覚可能な造形言語に変換する",
    design_lang_sub_ko: "문화적 이미지를 지각 가능한 조형 언어로 전환",
    design_lang_sub_ar: "تحويل الصور الثقافية إلى لغة شكلية ملموسة",
    design_lang_sub_de: "Kulturelle Bilder in wahrnehmbare Formensprache übersetzen",
    design_lang_sub_fr: "Transformer les images culturelles en langage formel perceptible",
    fitness_label: "器械训练 · 有氧运动 · 体能提升",
    fitness_label_en: "Strength · Cardio · Conditioning",
    fitness_label_ja: "筋トレ · 有酸素 · コンディショニング",
    fitness_label_ko: "근력 · 유산소 · 체력단련",
    fitness_label_ar: "قوة · كارديو · لياقة",
    fitness_label_de: "Kraft · Cardio · Kondition",
    fitness_label_fr: "Musculation · Cardio · Conditionnement",
    email: "3323798056@qq.com",
    phone: "+86 135 6007 8021",
    contact_big: "让我们一起<br>做些<em>有意思</em>的<br>事情。",
    contact_big_en: "Let's build<br>something <em>interesting</em><br>together.",
    contact_big_ja: "一緒に<br><em>面白い</em>ことを<br>しましょう。",
    contact_big_ko: "함께<br><em>재미있는</em> 일을<br>해봅시다.",
    contact_big_ar: "لنبنِ<br>شيئاً <em>مثيراً</em><br>معاً.",
    contact_big_de: "Lass uns gemeinsam<br>etwas <em>Interessantes</em><br>schaffen.",
    contact_big_fr: "Construisons<br>quelque chose<br>d'<em>intéressant</em> ensemble.",
    hero_photo: "",
    hero_photo_en: "",
    hero_photo_ja: "",
    hero_photo_ko: "",
    hero_photo_ar: "",
    hero_photo_de: "",
    hero_photo_fr: ""
};

// ==================== ABOUT ====================
var ABOUT = {
    p1: "我是陈文亮，广州美术学院汽车设计方向的学生。相信好的设计不止于功能与形式的统一——它应该承载文化记忆、触发情感共鸣，并在观者心中留下某种「意境」。",
    p1_en: "I'm Wenliang Chen, an automotive design student at GAFA. I believe great design goes beyond the unity of function and form — it should carry cultural memory, trigger emotional resonance, and leave an 'impression' in the viewer's mind.",
    p1_ja: "私は陳文亮、広州美術学院の自動車デザイン方向の学生です。良いデザインとは機能と形式の統一にとどまらない——文化的記憶を運び、情感的共鳴を呼び起こし、見る者の心に「意境」を残すべきだと信じています。",
    p1_ko: "나는 천원량, 광저우미술학원 자동차디자인 전공 학생이다. 좋은 디자인은 기능과 형식의 통일에 그치지 않는다——문화적 기억을 담고, 감정적 공명을 일으키며, 보는 이의 마음에 '의경'을 남겨야 한다고 믿는다.",
    p1_ar: "أنا تشن ونليانغ، طالب تصميم سيارات في أكاديمية غوانجو للفنون الجميلة. أؤمن بأن التصميم الجيد لا يقتصر على توحيد الوظيفة والشكل — بل يجب أن يحمل الذاكرة الثقافية، ويثير صدى عاطفياً، ويترك \"أجواء\" في ذهن المشاهد.",
    p1_de: "Ich bin Wenliang Chen, Student der Fahrzeugdesign-Richtung an der GAFA. Ich glaube, dass gutes Design über die Einheit von Funktion und Form hinausgeht — es sollte kulturelle Erinnerung tragen, emotionale Resonanz auslösen und eine \"Stimmung\" im Betrachter hinterlassen.",
    p1_fr: "Je suis Wenliang Chen, étudiant en design automobile à la GAFA. Je crois qu'un bon design ne se limite pas à l'unité de la fonction et de la forme — il doit porter la mémoire culturelle, susciter une résonance émotionnelle et laisser une « impression » dans l'esprit du spectateur.",
    p2: "我的设计实践围绕东方美学展开：从丝绸文化到邮轮造型，从情感化汽车设计到概念 SUV，我尝试将传统文化意象转化为当代设计语言。每一个项目都是一次叙事——关于过去与未来的对话。",
    p2_en: "My design practice revolves around Eastern aesthetics: from silk culture to cruise form, from emotional automotive design to concept SUVs. I transform traditional cultural imagery into contemporary design language. Every project is a narrative — a dialogue between past and future.",
    p2_ja: "私のデザイン実践は東洋美学を中心に展開しています：シルク文化からクルーズ船の造型まで、感情豊かな自動車デザインからコンセプトSUVまで、伝統的な文化イメージを現代的なデザイン言語に変換しようと試みています。それぞれのプロジェクトは一つの物語——過去と未来の対話です。",
    p2_ko: "나의 디자인 실천은 동양미학을 중심으로 전개된다: 실크 문화에서 크루즈선 조형까지, 감성적 자동차 디자인에서 컨셉 SUV까지, 전통 문화 이미지를 현대적 디자인 언어로 변환하려 한다. 모든 프로젝트는 하나의 서사 — 과거와 미래의 대화다.",
    p2_ar: "تتمحور ممارستي التصميمية حول الجماليات الشرقية: من ثقافة الحرير إلى شكل السفن السياحية، ومن تصميم السيارات العاطفي إلى سيارات الدفع الرباعي المفاهيمية، أحاول تحويل الصور الثقافية التقليدية إلى لغة تصميم معاصرة. كل مشروع هو سرد — حوار بين الماضي والمستقبل.",
    p2_de: "Meine Designpraxis dreht sich um östliche Ästhetik: Von Seidenkultur bis Schiffsform, von emotionalem Fahrzeugdesign bis Konzept-SUV — ich versuche, traditionelle kulturelle Bilder in zeitgenössische Designsprache zu übersetzen. Jedes Projekt ist eine Erzählung — ein Dialog zwischen Vergangenheit und Zukunft.",
    p2_fr: "Ma pratique du design s'articule autour de l'esthétique orientale : de la culture de la soie à la forme des paquebots, du design automobile émotionnel au SUV conceptuel, je tente de transformer les images culturelles traditionnelles en langage design contemporain. Chaque projet est une narration — un dialogue entre passé et futur.",
    p3: "与此同时，我也热爱健身。设计中的比例感与结构思维，同样适用于对身体的雕刻。两者看似无关，实则共享同一种底层逻辑——对细节的敏感，对结构的理解，对「美」与「健康」的追求。",
    p3_en: "Meanwhile, I'm also passionate about fitness. The sense of proportion and structural thinking from design applies equally to sculpting the body. The two may seem unrelated, but share the same underlying logic — sensitivity to detail, understanding of structure, and pursuit of 'beauty' and 'health'.",
    p3_ja: "同時に、フィットネスも愛しています。デザインにおける比例感や構造思考は、身体の造形にもそのまま適用できます。一見無関係な二つですが、実は同じ論理を共有しています——細部への_SENSITIVITY_、構造への理解、「美」と「健康」の追求。",
    p3_ko: "동시에 나는 피트니스를 사랑한다. 디자인의 비례감과 구조적 사고는 신체의 조각에도 그대로 적용된다. 언뜻 무관해 보이는 두 가지지만, 사실 같은 논리를 공유한다 — 세부에 대한 민감성, 구조에 대한 이해, '아름다움'과 '건강'에 대한 추구.",
    p3_ar: "في الوقت نفسه، أنا شغوف باللياقة. الإحساس بالتناسب والتفكير الهيكلي في التصميم ينطبقان أيضاً على نحت الجسم. قد يبدو الأمران غير مرتبطين، لكنهما يشتركان في نفس المنطق — الحساسية للتفاصيل، فهم البنية، والسعي وراء \"الجمال\" و\"الصحة\".",
    p3_de: "Gleichzeitig bin ich leidenschaftlich beim Fitness. Das Proportionsgefühl und strukturelle Denken im Design lässt sich ebenso auf die Körpergestaltung anwenden. Beide scheinen unrelated, teilen aber dieselbe Logik — Sensibilität für Details, Verständnis für Struktur und das Streben nach \"Schönheit\" und \"Gesundheit\".",
    p3_fr: "Parallèlement, je suis passionné par le fitness. Le sens des proportions et la pensée structurelle du design s'appliquent également à la sculpture du corps. Les deux peuvent sembler sans rapport, mais partagent la même logique — sensibilité aux détails, compréhension de la structure et poursuite de la « beauté » et de la « santé »."
};

// ==================== WORKS ====================
var WORKS = [
    {
        tag: "汽车设计",
        tag_en: "Automotive Design",
        tag_ja: "自動車デザイン",
        tag_ko: "자동차디자인",
        tag_ar: "تصميم السيارات",
        tag_de: "Fahrzeugdesign",
        tag_fr: "Design Automobile",
        year: "2026",
        title: "Alfa Romeo Otto Vittoria 33",
        title_en: "Alfa Romeo Otto Vittoria 33",
        title_ja: "Alfa Romeo Otto Vittoria 33",
        title_ko: "Alfa Romeo Otto Vittoria 33",
        title_ar: "Alfa Romeo Otto Vittoria 33",
        title_de: "Alfa Romeo Otto Vittoria 33",
        title_fr: "Alfa Romeo Otto Vittoria 33",
        desc: "致敬经典赛车的限量概念超跑，传承 Vittorio Jano 的黄金时代设计灵魂",
        desc_en: "A limited-edition concept supercar paying tribute to the golden era of Vittorio Jano",
        desc_ja: "ヴィットリオ・ヤーノの黄金時代へのオマージュ。限定コンセプトスーパーカー",
        desc_ko: "비토리오 야노의 황금시대에 바치는 경의. 한정판 컨셉 슈퍼카",
        desc_ar: "سيارة كونسيبت فريدة محدودة الإصدار تحية للعصر الذهبي ل فيتوريو جانو",
        desc_de: "Eine limitierte Konzept-Supercar-Huldigung an die goldene Ära von Vittorio Jano",
        desc_fr: "Un supercar concept en édition limitée rendant hommage à l'âge d'or de Vittorio Jano",
        icon: "◆",
        image: "photos/alfa/alfa_01_03.jpg",
        gallery: [
            "photos/alfa/alfa_01_03.jpg",
            "photos/alfa/alfa_02_03.jpg",
            "photos/alfa/alfa_03_03.jpg",
            "photos/alfa/alfa_04.jpg",
            "photos/alfa/alfa_05.jpg",
            "photos/alfa/alfa_06.jpg",
            "photos/alfa/alfa_07.jpg",
            "photos/alfa/alfa_08.jpg",
            "photos/alfa/alfa_09_03.jpg",
            "photos/alfa/alfa_10.jpg"
        ]
    },
    {
        tag: "汽车设计",
        tag_en: "Automotive Design",
        tag_ja: "自動車デザイン",
        tag_ko: "자동차디자인",
        tag_ar: "تصميم السيارات",
        tag_de: "Fahrzeugdesign",
        tag_fr: "Design Automobile",
        year: "2026",
        title: "悍马 · 荒雅",
        title_en: "HUMMER · Huangya",
        title_ja: "ハマー · 荒雅",
        title_ko: "허머 · 황아",
        title_ar: "هامر · هوانغيا",
        title_de: "HUMMER · Huangya",
        title_fr: "HUMMER · Huangya",
        desc: "荒野不是绝望之地，而是盛宴之所——将战士精神注入现代越野车设计",
        desc_en: "The wilderness is not despair but a feast — injecting warrior spirit into modern off-road design",
        desc_ja: "荒野は絶望の地ではなく宴の場——戦士の精神を現代オフロードデザインに注ぐ",
        desc_ko: "황야는 절망의 땅이 아닌 연회의 장소 — 전사의 정신을 현대 오프로드 디자인에 주입",
        desc_ar: "البرية ليست يأساً بل مأدبة — حقن روح المحارب في تصميم الطرق الوعرة الحديثة",
        desc_de: "Die Wildnis ist nicht Verzweiflung, sondern ein Fest — Kriegergeist wird in modernes Offroad-Design injiziert",
        desc_fr: "La nature sauvage n'est pas le désespoir mais un festin — injection de l'esprit guerrier dans le design tout-terrain moderne",
        icon: "◇",
        image: "photos/hummer/hummer_01.jpg",
        gallery: [
            "photos/hummer/hummer_01.jpg",
            "photos/hummer/hummer_02.jpg",
            "photos/hummer/hummer_03.jpg",
            "photos/hummer/hummer_04.jpg",
            "photos/hummer/hummer_05.jpg",
            "photos/hummer/hummer_06.jpg",
            "photos/hummer/hummer_07.jpg",
            "photos/hummer/hummer_08.jpg",
            "photos/hummer/hummer_09.jpg",
            "photos/hummer/hummer_10.jpg",
            "photos/hummer/hummer_11.jpg",
            "photos/hummer/hummer_12.jpg",
            "photos/hummer/hummer_13.jpg",
            "photos/hummer/hummer_14.jpg",
            "photos/hummer/hummer_15.jpg"
        ]
    },
    {
        tag: "汽车设计",
        tag_en: "Automotive Design",
        tag_ja: "自動車デザイン",
        tag_ko: "자동차디자인",
        tag_ar: "تصميم السيارات",
        tag_de: "Fahrzeugdesign",
        tag_fr: "Design Automobile",
        year: "2082",
        title: "Tesla Eclipse",
        title_en: "Tesla Eclipse",
        title_ja: "Tesla Eclipse",
        title_ko: "Tesla Eclipse",
        title_ar: "Tesla Eclipse",
        title_de: "Tesla Eclipse",
        title_fr: "Tesla Eclipse",
        desc: "Project Eclipse — 2082年特斯拉高端双座概念车，驶离黑暗的最后一次日出",
        desc_en: "Project Eclipse — 2082 Tesla high-end two-seater concept, the last sunrise driving away darkness",
        desc_ja: "Project Eclipse — 2082年テスラ高端ツインシートコンセプト。暗闇を走り去る最後の日の出",
        desc_ko: "Project Eclipse — 2082년 테슬라 하이엔드 2인승 컨셉트. 어둠을 몰고 가는 마지막 일출",
        desc_ar: "Project Eclipse — 2082 سيارة تسلا فاخرة ذات مقعدين. آخر شروق يقود بعيداً عن الظلام",
        desc_de: "Project Eclipse — 2082 Tesla High-End Zweisitzer-Konzept. Der letzte Sonnenaufgang, der die Dunkelheit vertreibt",
        desc_fr: "Project Eclipse — 2082 Tesla biplace haut de gamme. Le dernier lever de soleil chassant les ténèbres",
        icon: "△",
        image: "photos/tesla/tesla_01.jpg",
        gallery: [
            "photos/tesla/tesla_01.jpg",
            "photos/tesla/tesla_02.jpg",
            "photos/tesla/tesla_03.jpg",
            "photos/tesla/tesla_04.jpg",
            "photos/tesla/tesla_05.jpg",
            "photos/tesla/tesla_06.jpg",
            "photos/tesla/tesla_07.jpg",
            "photos/tesla/tesla_08.jpg",
            "photos/tesla/tesla_09.jpg",
            "photos/tesla/tesla_10.jpg",
            "photos/tesla/tesla_11.jpg",
            "photos/tesla/tesla_12.jpg"
        ]
    },
    {
        tag: "汽车设计",
        tag_en: "Automotive Design",
        tag_ja: "自動車デザイン",
        tag_ko: "자동차디자인",
        tag_ar: "تصميم السيارات",
        tag_de: "Fahrzeugdesign",
        tag_fr: "Design Automobile",
        year: "2026",
        title: "Volvo Embers",
        title_en: "Volvo Embers",
        title_ja: "Volvo Embers",
        title_ko: "Volvo Embers",
        title_ar: "Volvo Embers",
        title_de: "Volvo Embers",
        title_fr: "Volvo Embers",
        desc: "传承1800ES基因的豪华电动轿跑——深色车身如冬夜，勃艮第座椅如不灭余烬",
        desc_en: "A luxury EV coupe inheriting 1800ES DNA — dark body like winter night, burgundy seats like undying embers",
        desc_ja: "1800ESのDNAを継承する豪華EVクーペ——濃い車体は冬の夜のよう、バーガンディシートは消えぬ残り火",
        desc_ko: "1800ES의 유전자를 계승한 럭셔리 EV 쿠페 — 어두운 차체는 겨울밤처럼, 버건디 시트는 사그라지지 않는 불씨처럼",
        desc_ar: "سيارة كوبيه كهربائية فاخرة تحمل جينات 1800ES — جسم داكن كليلة شتوي، مقاعد بورغندية كجمرة لا تنطفئ",
        desc_de: "Ein luxuriöses E-Coupé mit dem Erbe des Volvo 1800ES — dunkle Karosserie wie Winternacht, burgunderfarbene Sitze wie unsterbliche Glut",
        desc_fr: "Un coupé électrique de luxe héritant de l'ADN du Volvo 1800ES — carrosserie sombre comme la nuit d'hiver, sièges bordeaux comme des braises éternelles",
        icon: "✦",
        image: "photos/volvo/volvo_01.jpg",
        gallery: [
            "photos/volvo/volvo_01.jpg",
            "photos/volvo/volvo_02.jpg",
            "photos/volvo/volvo_03.jpg",
            "photos/volvo/volvo_04.jpg",
            "photos/volvo/volvo_05.jpg",
            "photos/volvo/volvo_06.jpg",
            "photos/volvo/volvo_07.jpg",
            "photos/volvo/volvo_08.jpg",
            "photos/volvo/volvo_09.jpg",
            "photos/volvo/volvo_10.jpg",
            "photos/volvo/volvo_11.jpg",
            "photos/volvo/volvo_12.jpg"
        ]
    }
];
// ==================== PROJECTS ====================
var PROJECTS = [
    {
        year: "26",
        title: "潮汐 · 织造 — <span>邮轮设计</span>",
        title_en: "Tide · Weaving — <span>Cruise Design</span>",
        title_ja: "潮汐 · 織造 — <span>クルーズデザイン</span>",
        title_ko: "조석 · 직조 — <span>크루즈 디자인</span>",
        title_ar: "المد والنسيج — <span>تصميم السفن السياحية</span>",
        title_de: "Gezeiten · Weberei — <span>Schiffsdesign</span>",
        title_fr: "Marées · Tissage — <span>Design de Paquebot</span>",
        desc: "以蚕的生命周期为叙事骨架——船首如结茧，船中如化蛹，船尾如破茧。四象意象（蚕·郑和·麒麟·牡丹）编织出从海上丝绸之路到当代东方美学的完整叙事。船体当织机，外观是正在被织出的丝绸。",
        desc_en: "With the silkworm's life cycle as narrative backbone — bow like cocoon, midship like chrysalis, stern like emergence. Four symbols (Silkworm, Zheng He, Qilin, Peony) weave a complete narrative from the Maritime Silk Road to contemporary Eastern aesthetics. The hull is a loom; the exterior is silk being woven.",
        desc_ja: "蚕の生命周期をナラティブの骨格に——船首は繭、船中は蛹、船尾は羽化。四つの象徴（蚕·鄭和·麒麟·牡丹）が海上シルクロードから現代の東洋美学までの完全な物語を織りなす。船体は織機、外観は織られゆくシルク。",
        desc_ko: "누에의 생애주기를 서사의 골격으로 — 뱃머리는 고치, 선중은 번데기, 선미는 우화. 사상의 상(누에·정화·기린·모란)이 해상 실크로드에서 현대 동양미학까지의 완전한 서사를 직조한다. 선체는 직조기, 외관은 직조되는 비단.",
        desc_ar: "دورة حياة دودة القز كهيكل سردي — المقدمة كالشرنقة، والوسط كالشرنقة، والمؤخرة كالفراشة. أربع رموز (دودة القز، تشنغ خه، كيلين، الفاوانيا) تنسج سرداً كاملاً من طريق الحرير البحري إلى الجماليات الشرقية المعاصرة.",
        desc_de: "Der Lebenszyklus der Seidenraupe als narrative Grundlage — Bug wie Kokon, Mitte wie Puppe, Heck wie Schlupf. Vier Symbole (Seidenraupe, Zheng He, Qilin, Pfingstrose) weben eine vollständige Erzählung von der maritimen Seidenstraße bis zur zeitgenössischen östlichen Ästhetik.",
        desc_fr: "Le cycle de vie du ver à soie comme ossature narrative — la proue comme cocon, le milieu comme chrysalide, la poupe comme émergence. Quatre symboles (Ver à soie, Zheng He, Qilin, Pivoine) tissent un récit complet de la Route maritime de la Soie à l'esthétique orientale contemporaine.",
        tags: ["邮轮设计", "东方美学", "文化叙事", "丝绸意象"],
        tags_en: ["Cruise Design", "Eastern Aesthetic", "Cultural Narrative", "Silk Motif"],
        tags_ja: ["クルーズデザイン", "東洋美学", "文化ナラティブ", "シルク"],
        tags_ko: ["크루즈디자인", "동양미학", "문화서사", "실크"],
        tags_ar: ["تصميم السفن", "جماليات شرقية", "سرد ثقافي", "حرير"],
        tags_de: ["Schiffsdesign", "Östliche Ästhetik", "Kulturelle Erzählung", "Seide"],
        tags_fr: ["Design de Paquebot", "Esthétique Orientale", "Narration Culturelle", "Soie"],
        detail: "「最柔软的材料，只能用来连接。」潮汐·织造颠覆了传统邮轮外饰设计的底层逻辑：不是将文化符号贴到船体表面，而是让船体本身成为织造行为的隐喻。四象叙事（蚕·郑和·麒麟·牡丹）分别对应自然、文明、价值、繁荣四个尺度——蚕吐丝是开始，郑和远航是传递，妈妈织衣是包裹，牡丹盛放是终点。船体以墨色、靛蓝、素白、云锦金、牡丹红六色构建色彩叙事，经纬织纹从船首至船尾经历密→疏→回旋的渐变。夜间灯光如梭子沿经纬线流动，使整艘船成为一台永不停歇的巨型织机。茧即栖居——深蓝之上，用丝绸编织一个会呼吸的家。",
        detail_en: "'The softest material can only be used to connect.' Tide · Weaving subverts the logic of cruise exterior design: instead of pasting cultural symbols onto the hull, the ship itself becomes a metaphor for weaving. Four symbols (Silkworm, Zheng He, Qilin, Peony) correspond to nature, civilization, value, and prosperity — silkworm spinning is the beginning, Zheng He's voyage is the transmission, mother weaving is the embrace, peony blooming is the culmination. Six colors (ink, indigo, white, cloud-brocade gold, peony red) build a chromatic narrative, with warp-weft patterns transitioning from dense to sparse to spiraling from bow to stern. Night lighting flows like a shuttle along the warp threads, turning the entire ship into a giant loom that never stops. The cocoon is a dwelling — above the deep blue, breathing life woven from silk.",
        detail_ja: "「最も柔らかい素材は、つなぐことだけに使える。」潮汐・織造は伝統的なクルーズ外装デザインの基礎論理を覆す：文化記号を船体に貼り付けるのではなく、船体そのものを織造行為の隠喩とする。四象ナラティブ（蚕・鄭和・麒麟・牡丹）はそれぞれ自然、文明、価値、繁栄の四つの尺度に対応する。船体は墨色、藍、素白、雲錦金、牡丹紅の六色で色彩ナラティブを構築し、経緯織紋は船首から船尾へ密→疎→回旋と変化していく。",
        detail_ko: "\"가장 부드러운 재료는, 오직 연결하기 위해서만 사용할 수 있다.\" 조석·직조는 전통적 크루즈 외장 디자인의 근본적 논리를 전복시킨다: 문화 기호를 선체에 붙이는 것이 아니라, 선체 자체가 직조 행위의 은유가 된다. 사상 서사(누에·정화·기린·모란)는 각각 자연, 문명, 가치, 번영의 네 가지 척도에 대응한다. 선체는 묵색, 남색, 소백, 운금금, 모란홍의 육색으로 색채 서사를 구축하고, 경위 직문은 뱃머리에서 선미까지 밀→소→회전의 변화를 겪는다.",
        detail_ar: "\"أنعم المواد لا يمكن استخدامه إلا للربط.\" يجسد المد والنسيج منطق التصميم التقليدي للسفن السياحية: بدلاً من لصق الرموز الثقافية على سطح السفينة، تصبح السفينة نفسها استعارة لعملية النسيج. السرد الرباعي (دودة القز، تشنغ خه، كيلين، الفاوانيا) يتوافق مع الطبيعة والحضارة والقيمة والازدهار.",
        detail_de: "\"Das weichste Material kann nur zum Verbinden verwendet werden.\" Tide · Weberei stellt die Grundlagenlogik des traditionellen Kreuzfahrt-Exterieurdesigns auf den Kopf: Anstatt kulturelle Symbole auf den Rumpf zu kleben, wird das Schiff selbst zur Metapher des Webens. Die Vier-Symbole-Erzählung (Seidenraupe, Zheng He, Qilin, Pfingstrose) entspricht den vier Maßstäben Natur, Zivilisation, Wert und Wohlstand.",
        detail_fr: "« Le matériau le plus doux ne peut être utilisé que pour connecter. » Marées · Tissage bouleverse la logique fondamentale du design extérieur traditionnel des paquebots : au lieu de coller des symboles culturels sur la coque, le navire lui-même devient une métaphore du tissage. La narration aux quatre symboles (Ver à soie, Zheng He, Qilin, Pivoine) correspond aux quatre échelles de la nature, de la civilisation, de la valeur et de la prospérité."
    },
    {
        year: "26",
        title: "比亚迪设计大赛 — <span>情感化汽车设计</span>",
        title_en: "BYD Design Contest — <span>Emotional Auto Design</span>",
        title_ja: "BYDデザインコンテスト — <span>感情化自動車デザイン</span>",
        title_ko: "BYD 디자인 공모전 — <span>감성적 자동차 디자인</span>",
        title_ar: "مسابقة BYD للتصميم — <span>تصميم سيارات عاطفي</span>",
        title_de: "BYD Designwettbewerb — <span>Emotionales Fahrzeugdesign</span>",
        title_fr: "Concours Design BYD — <span>Design Automobile Émotionnel</span>",
        desc: "主赛道「万象朝新」参赛作品。以夏朝'水镜'为核心隐喻——大禹治水十三年不归，洪水退去人回来，水面平静一家人围坐照见彼此。MPV是水面，茶几是镜子。别离·团圆·照见，一辆移动的东方家空间。",
        desc_en: "BYD 'Wanxiang Zhaoxin' contest entry. Using the Xia Dynasty 'water mirror' as core metaphor: Yu the Great spent 13 years taming floods, never returning home. When the waters receded, the surface went still, and the family sat together seeing each other's reflections. The MPV is the water, the tea table is the mirror. A mobile Eastern living room.",
        desc_ja: "メイントラック「万象朝新」出品作品。夏朝の「水鏡」を核心的メタファーに——大禹は13年間治水に明け暮れ帰らず、洪水が引き人が戻り、水面が穏やかになり家族が寄り座り互いを映す。MPVは水面、茶台は鏡。別離・再会・映し合い、移動する東洋の家族空間。",
        desc_ko: "메인 트랙 '만상조신' 출품작. 하조 '수경'을 핵심 은유로 — 대우가 13년간 치수에 전념하며 돌아가지 않고, 홍수가 물러가고 사람이 돌아오고, 수면이 잔잔해져 가족이 둘러앉아 서로를 비춘다. MPV는 수면, 찻상은 거울. 이별·재회·비춤, 움직이는 동양의 가정 공간.",
        desc_ar: "عمل مشارك في المسار الرئيسي \"وانشيانغ تشاو شين\". باستخدام \"مرآة الماء\" من أسرة شيا كاستعارة أساسية: قضى يو العظيم 13 عاماً في ترويض الفيضانات دون العودة. عندما انسحبت المياه، هدأ السطح، وجلست العائلة معاً ترى انعكاساتها. الـ MPV هو الماء، وطاولة الشاي هي المرآة.",
        desc_de: "Beitrag zum Hauptwettbewerb \"Wanxiang Zhaoxin\". Mit der Xia-Dynastie \"Wasserspiegel\" als Kernmetapher — Yu der Große verbrachte 13 Jahre mit der Bändigung der Fluten, ohne heimzukehren. Als das Wasser zurücktrat, wurde die Oberfläche still, und die Familie saß zusammen und sah sich gegenseitig. Der MPV ist das Wasser, der Teetisch ist der Spiegel.",
        desc_fr: "Contribution à la voie principale « Wanxiang Zhaoxin ». Utilisant le « miroir d'eau » de la dynastie Xia comme métaphore centrale : Yu le Grand a passé 13 ans à dompter les inondations sans rentrer. Quand les eaux se sont retirées, la surface est devenue calme, et la famille s'est assise ensemble se reflétant mutuellement. Le MPV est l'eau, la table à thé est le miroir.",
        tags: ["汽车设计", "情感化设计", "BYD"],
        tags_en: ["Auto Design", "Emotional Design", "BYD"],
        tags_ja: ["自動車デザイン", "感情化デザイン", "BYD"],
        tags_ko: ["자동차디자인", "감성디자인", "BYD"],
        tags_ar: ["تصميم السيارات", "تصميم عاطفي", "BYD"],
        tags_de: ["Fahrzeugdesign", "Emotionales Design", "BYD"],
        tags_fr: ["Design Auto", "Design Émotionnel", "BYD"],
        detail: "比亚迪设计大赛「万象朝新」赛道参赛作品，作品《中庭·行》，车型命名庭镜/MiraCourt，定位比亚迪夏系列MPV。设计哲学：别离·团圆·照见。核心隐喻源自大禹治水十三年不归的古老叙事——洪水退去人回来，水面平静如镜，一家人围坐照见彼此。MPV是水面，茶几是镜子。广告语：「庭镜所至，心之所归」「水等风停，庭等人归」。色调取自夏朝玉器、青铜、水波纹，走「久别重逢的清冽」路线，与比亚迪夏系列现有的「盛世华美」形成差异化。",
        detail_en: "BYD Design Contest 'Wanxiang Zhaoxin' track entry. Work titled 'The Central Court · Journey', vehicle named MiraCourt, positioned as BYD Xia series MPV. Design philosophy: Parting, Reunion, Reflection. Core metaphor from Yu the Great's 13-year flood control — when waters receded, the surface became still as a mirror, and the family sat together seeing each other. The MPV is the water, the tea table is the mirror. Taglines: 'Where the court mirrors, the heart returns' / 'Water waits for wind to stop, the court waits for you to come home'. Color palette from Xia Dynasty jade, bronze, and water ripples. A 'long-awaited reunion clarity' approach, differentiating from BYD Xia's existing 'prosperous beauty'.",
        detail_ja: "BYDデザインコンテスト「万象朝新」トラック出品作品。作品名「中庭·行」、車名は庭鏡/MiraCourt、BYD夏シリーズMPVとして位置づけ。デザイン哲学：別離・再会・映し合い。コアメタファーは大禹の13年間の治水に由来する。MPVは水面、茶台は鏡。「庭鏡至る所、心の帰る所」「水は風が止まるを待ち、庭は人の帰りを待つ」。夏朝の玉器、青銅、水波紋から取った色調。",
        detail_ko: "BYD 디자인 공모전 '만상조신' 트랙 출품작. 작품명 '중정·행', 차명 정원/MiraCourt, BYD 하 시리즈 MPV로 포지셔닝. 디자인 철학: 이별·재회·비춤. 핵심 은유는 대우의 13년간 치수 이야기에서 유래. MPV는 수면, 찻상은 거울. \"정원이 비추는 곳, 마음이 돌아가는 곳\" / \"물은 바람이 멈추길 기다리고, 정은 사람이 돌아오길 기다린다\". 하조의 옥기, 청동, 수파문에서 추출한 색조.",
        detail_ar: "عمل مشارك في مسار \"وانشيانغ تشاو شين\" بمسابقة BYD للتصميم. العمل بعنوان \"الفناء الأوسط · الرحلة\"، السيارة命名为 MiraCourt، مصممة كسيارة MPV من سلسلة BYD Xia. فلسفة التصميم: الفراق، لم الشمل، الانعكاس. الاستعارة الأساسية مستمدة من قصة يو العظيم في السيطرة على الفيضانات على مدى 13 عاماً.",
        detail_de: "Beitrag zum BYD Designwettbewerb \"Wanxiang Zhaoxin\". Werk \"Der zentrale Hof · Reise\", Fahrzeug MiraCourt, positioniert als BYD Xia Serie MPV. Designphilosophie: Trennung, Wiedersehen, Spiegelung. Kernmetapher aus Yu des Großen 13-jähriger Flutkontrolle. Der MPV ist das Wasser, der Teetisch ist der Spiegel. Farbpalette aus Xia-Dynastie-Jade, Bronze und Wasserwellen.",
        detail_fr: "Contribution au concours BYD « Wanxiang Zhaoxin ». Œuvre « La Cour Centrale · Voyage », véhicule nommé MiraCourt, positionné comme MPV de la série BYD Xia. Philosophie de design : Séparation, Réunions, Réflexion. Métaphore centrale de Yu le Grand et ses 13 ans de contrôle des inondations. Le MPV est l'eau, la table à thé est le miroir. Palette de couleurs inspirée de la jade, du bronze et des ondulations de la dynastie Xia."
    },
    {
        year: "2082",
        title: "Tesla Eclipse — <span>最后的日出</span>",
        title_en: "Tesla Eclipse — <span>The Last Sunrise</span>",
        title_ja: "Tesla Eclipse — <span>最後の日の出</span>",
        title_ko: "Tesla Eclipse — <span>마지막 일출</span>",
        title_ar: "Tesla Eclipse — <span>آخر شروق</span>",
        title_de: "Tesla Eclipse — <span>Der letzte Sonnenaufgang</span>",
        title_fr: "Tesla Eclipse — <span>Le Dernier Lever</span>",
        desc: "Project Eclipse — 2082年特斯拉高端双座概念车。在一个被自动驾驶统治的未来，这是为仍然渴望驾驶乐趣的人设计的最后礼物——驶离黑暗的最后一次日出。",
        desc_en: "Project Eclipse — 2082 Tesla high-end two-seater concept. The last gift for those who still crave driving pleasure in an autonomous future.",
        desc_ja: "Project Eclipse — 2082年テスラのハイエンド2人乗りコンセプト。自動運転が支配する未来で、まだ運転の喜びを渇望する人々への最後の贈り物——闇を走り去る最後の日の出。",
        desc_ko: "Project Eclipse — 2082년 Tesla 하이엔드 2인승 컨셉트. 자율주행이 지배하는 미래에서 여전히 운전의 즐거움을 갈망하는 사람들을 위한 마지막 선물 — 어둠을 몰고 가는 마지막 일출.",
        desc_ar: "Project Eclipse — 2082 سيارة تسلا فاخرة ذات مقعدين. آخر هدية لأولئك الذين لا يزالون يسعون لمتعة القيادة في مستقبل تحكمه القيادة الذاتية.",
        desc_de: "Project Eclipse — 2082 Tesla High-End Zweisitzer-Konzept. Das letzte Geschenk für alle, die in einer autonomen Zukunft noch nach Fahrvergnügen sehnen.",
        desc_fr: "Project Eclipse — 2082 Tesla biplace haut de gamme. Le dernier cadeau pour ceux qui aspirent encore au plaisir de conduire dans un avenir autonome.",
        tags: ["未来概念", "双座跑车", "情感设计"],
        tags_en: ["Future Concept", "Two-Seater", "Emotional Design"],
        tags_ja: ["未来コンセプト", "2人乗り", "エモーショナルデザイン"],
        tags_ko: ["미래 컨셉", "두 자리", "이모셔널 디자인"],
        tags_ar: ["مفهوم مستقبلي", "مقعدين", "تصميم عاطفي"],
        tags_de: ["Zukunftskonzept", "Zweisitzer", "Emotionales Design"],
        tags_fr: ["Concept Futuriste", "Biplace", "Design Émotionnel"],
        detail: "2082年，自动驾驶已完全普及，人类驾驶成为稀缺的奢侈体验。Tesla Eclipse 是为那些仍然渴望掌控方向盘的人打造的终极座驾。设计主题是「日蚀」——光明与黑暗的交界处，人类意志与机器智能的对话。流线型车身如同如同被黑暗包围的光，暗示着这是人类驾驶的最后辉煌。",
        detail_en: "In 2082, autonomous driving is fully prevalent, and human driving has become a scarce luxury experience. Tesla Eclipse is the ultimate ride crafted for those who still crave to hold the steering wheel. The design theme is 'Eclipse' — the boundary between light and darkness, a dialogue between human will and machine intelligence. The streamlined body is like light surrounded by darkness, hinting that this is the last glory of human driving.",
        detail_ja: "2082年、自動運転が完全に普及し、人間の運転は希少な高級体験となった。Tesla Eclipse はまだハンドルを握りたいと願う人々のための究極の乗り物。デザインテーマは「日蝕」——光と闇の境界、人間の意志と機械知能の対話。流線型のボディは闇に囲まれた光のようであり、これが人類運転の最後の輝きであることを示唆している。",
        detail_ko: "2082년, 자율주행이 완전히 보편화되어 인간 운전은 희소한 럭셔리 체험이 되었다. Tesla Eclipse는 여전히 핸들을 잡고 싶은 사람들을 위한 궁극의坐骑. 디자인 테마는 '일식' — 빛과 어둠의 경계, 인간의 의지와 기계 지능의 대화. 유선형 차체는 어둠에 둘러싸인 빛과 같으며, 이것이 인간 운전의 마지막 찬란함을 암시한다.",
        detail_ar: "في عام 2082، أصبحت القيادة الذاتية شائعة بالكامل، وأصبحت القيادة البشرية تجربة فاخرة نادرة. Tesla Eclipse هي السيارة المطلقة المصممة لأولئك الذين لا يزالون يتوقون للإمساك بعجلة القيادة. موضوع التصميم هو \"الكسوف\" — الحدود بين الضوء والظلام، حوار بين الإرادة البشرية والذكاء الآلي.",
        detail_de: "Im Jahr 2082 ist autonomes Fahren vollständig verbreitet und menschliches Fahren ist zu einem seltenen Luxus geworden. Tesla Eclipse ist das ultimative Fahrzeug für jene, die sich noch nach dem Lenkrad sehnen. Das Design-Thema ist \"Eklipse\" — die Grenze zwischen Licht und Dunkelheit, ein Dialog zwischen menschlichem Willen und maschineller Intelligenz.",
        detail_fr: "En 2082, la conduite autonome est entièrement répandue et la conduite humaine est devenue une expérience de luxe rare. Tesla Eclipse est le véhicule ultime conçu pour ceux qui aspirent encore à tenir le volant. Le thème du design est « Éclipse » — la frontière entre lumière et obscurité, un dialogue entre la volonté humaine et l'intelligence artificielle."
    },
    {
        year: "26",
        title: "Volvo Embers — <span>不灭余烬</span>",
        title_en: "Volvo Embers — <span>Undying Embers</span>",
        title_ja: "Volvo Embers — <span>消えない余韻</span>",
        title_ko: "Volvo Embers — <span>사라지지 않는 불꽃</span>",
        title_ar: "Volvo Embers — <span>جمرة لا تنطفئ</span>",
        title_de: "Volvo Embers — <span>Unsterbliche Glut</span>",
        title_fr: "Volvo Embers — <span>Braises Éternelles</span>",
        desc: "传承 Volvo 1800ES 经典基因的豪华电动轿跑。深色车身如冬夜，勃艮第的内饰则是壁炉中永不熄灭的余烬。这不是复古，而是将经典的精神内核注入电动化的未来。",
        desc_en: "A luxury EV coupe inheriting Volvo 1800ES DNA. Dark body like winter night, burgundy seats like undying embers — Nordic warmth restrained in the electric age.",
        desc_ja: "Volvo 1800ESのクラシックなDNAを継承する豪華電動クーペ。ダークなボディは冬の夜のよう、バーガンディのインテリアは暖炉の中で決して消えない残り火。これは復古ではなく、クラシックな精神の核を電動化の未来に注入すること。",
        desc_ko: "Volvo 1800ES의 클래식 유전자를 계승한 럭셔리 전기차 쿠페. 어두운 차체는 겨울밤처럼, 버건디 인테리어는 벽난로 속 사라지지 않는 불씨. 이것은 복고가 아니라, 클래식한 정신의 핵을 전기동의 미래에 주입하는 것이다.",
        desc_ar: "سيارة كوبيه كهربائية فاخرة تحمل الجينات الكلاسيكية لـ Volvo 1800ES. الجسم الداكن كليلة شتوي، والديكور الداخلي البورغندي كجمرة لا تنطفئ في المدفأة. هذا ليس رجعية، بل حقن الجوهر الروحي الكلاسيكي في مستقبل الكهربة.",
        desc_de: "Ein luxuriöses E-Coupé mit dem klassischen Erbe des Volvo 1800ES. Dunkle Karosserie wie Winternacht, burgunderfarbene Innenausstattung wie unsterbliche Glut im Kamin. Dies ist keine Retro, sondern die Injektion des klassischen Geistes in die elektrifizierte Zukunft.",
        desc_fr: "Un coupé électrique de luxe héritant de l'ADN classique du Volvo 1800ES. Carrosserie sombre comme la nuit d'hiver, intérieur bordeaux comme des braises éternelles dans la cheminée. Ce n'est pas de la rétro, mais l'injection de l'esprit classique dans l'avenir électrifié.",
        tags: ["电动轿跑", "北欧设计", "经典传承"],
        tags_en: ["EV Coupe", "Nordic Design", "Classic Heritage"],
        tags_ja: ["EVクーペ", "北欧デザイン", "クラシック传承"],
        tags_ko: ["EV 쿠페", "북유럽 디자인", "클래식 계승"],
        tags_ar: ["سيارة كوبيه كهربائية", "تصميم شمالي", "تراث كلاسيكي"],
        tags_de: ["E-Coupé", "Nordisches Design", "Klassisches Erbe"],
        tags_fr: ["Coupé Électrique", "Design Nordique", "Héritage Classique"],
        detail: "Volvo Embers 的设计起点是1971年的 Volvo 1800ES——一款被誉为最美沃尔沃的经典猎装车。Embers（余烬）意味着火焰虽已熄灭，温度仍在。设计在北欧极简主义的基础上，注入了温暖的情感维度：深色车身象征北欧漫长的冬夜，勃艮第红的内饰则是壁炉中永不熄灭的余烬。这不是复古，而是将经典的精神内核注入电动化的未来。",
        detail_en: "The starting point for Volvo Embers is the 1971 Volvo 1800ES — a classic shooting brake hailed as the most beautiful Volvo. Embers means the flame may be out, but the warmth remains. Building on Nordic minimalism, the design injects a warm emotional dimension: the dark body symbolizes the long Nordic winter night, while the burgundy red interior is the undying ember in the fireplace. This is not retro — it's injecting the spiritual core of the classic into the electric future.",
        detail_ja: "Volvo Embersの出発点は1971年のVolvo 1800ES——最も美しいボルボと称されるクラシックシューティングブレーク。Embers（残り火）とは炎は消えても温度は残るということ。北欧ミニマリズムの上に、暖かい感情的次元を注入：ダークボディは北欧の長い冬夜を象徴し、バーガンディレッドのインテリアは暖炉の消えない残り火。これは復古ではなく、クラシックな精神の核を電動化の未来に注入すること。",
        detail_ko: "Volvo Embers의 출발점은 1971년 Volvo 1800ES — 가장 아름다운 볼보로 불리는 클래식 슈팅브레이크. Embers(불씨)는 불꽃은 꺼져도 온도는 남아있다는 뜻. 북유럽 미니멀리즘 위에 따뜻한 감성 차원을 주입: 어두운 차체는 북유럽의 긴 겨울밤을 상징하고, 버건디 레드 인테리어는 벽난로 속 사라지지 않는 불씨. 이것은 복고가 아니라, 클래식한 정신의 핵을 전동화의 미래에 주입하는 것이다.",
        detail_ar: "نقطة الانطلاق لـ Volvo Embers هي Volvo 1800ES لعام 1971 — سيارة كلاسيكية راقية تُعتبر أجمل فولفو. الجمرة تعني أن اللهب قد انطفأ لكن الحرارة لا تزال. على أساس الحد الأدنى الاسكندنافي، يضفي التصميم بُعداً عاطفياً دافئاً: الجسم الداكن يرمز إلى الليل الشتوي الاسكندنافي الطويل، والداخلية البورغندية هي الجمرة التي لا تنطفئ في المدفأة.",
        detail_de: "Der Ausgangspunkt für Volvo Embers ist der 1971 Volvo 1800ES — ein klassischer Shooting Brake, der als schönster Volvo gilt. Embers bedeutet, die Flamme mag erloschen sein, aber die Wärme bleibt. Auf skandinavischem Minimalismus aufbauend, injiziert das Design eine warme emotionale Dimension: die dunkle Karosserie symbolisiert die lange skandinavische Winternacht, während das burgunderrote Interieur die unsterbliche Glut im Kamin ist.",
        detail_fr: "Le point de départ de Volvo Embers est le Volvo 1800ES de 1971 — un shooting brake classique salué comme le plus beau Volvo. Embers signifie que la flamme s'est éteinte mais la chaleur demeure. Sur le minimalisme nordique, le design injecte une dimension émotionnelle chaleureuse : la carrosserie sombre symbolise la longue nuit d'hiver nordique, tandis que l'intérieur bordeaux est la braise éternelle dans la cheminée."
    },
    {
        year: "26",
        title: "上汽名爵 MG 寻星 — <span>概念SUV</span>",
        title_en: "SAIC MG Xunxing — <span>Concept SUV</span>",
        title_ja: "SAIC MG Xunxing — <span>コンセプトSUV</span>",
        title_ko: "SAIC MG Xunxing — <span>컨셉 SUV</span>",
        title_ar: "SAIC MG Xunxing — <span>سيارة概念 SUV</span>",
        title_de: "SAIC MG Xunxing — <span>Konzept-SUV</span>",
        title_fr: "SAIC MG Xunxing — <span>SUV Concept</span>",
        desc: "上汽名爵MG寻星概念SUV项目，融合东方美学与未来出行理念，探索星际探索主题下的新一代SUV设计语言。",
        desc_en: "SAIC MG Xunxing Concept SUV project, blending Eastern aesthetics with future mobility, exploring a new SUV design language inspired by interstellar exploration.",
        desc_ja: "SAIC MG XunxingコンセプトSUVプロジェクト。東洋美学と未来のモビリティを融合し、星間探索をテーマにした新世代SUVデザイン言語を探求。",
        desc_ko: "SAIC MG Xunxing 컨셉 SUV 프로젝트. 동양 미학과 미래 모빌리티를 융합하여 성간 탐사를 주제로 한 차세대 SUV 디자인 언어를 탐구.",
        desc_ar: "مشروع SAIC MG Xunxing SUV المفاهيمي، يجمع بين الجماليات الشرقية وتنقل المستقبل، ويستكشف لغة تصميم جديدة لسيارات الدفع الرباعي مستوحاة من الاستكشاف بين النجوم.",
        desc_de: "SAIC MG Xunxing Konzept-SUV-Projekt, das östliche Ästhetik mit zukünftiger Mobilität verbindet und eine neue SUV-Designsprache erforscht, inspiriert von interstellarer Exploration.",
        desc_fr: "Projet SUV concept SAIC MG Xunxing, mêlant esthétique orientale et mobilité future, explorant un nouveau langage de design SUV inspiré de l'exploration interstellaire.",
        tags: ["概念SUV", "上汽名爵", "未来出行", "东方美学"],
        tags_en: ["Concept SUV", "SAIC MG", "Future Mobility", "Eastern Aesthetics"],
        tags_ja: ["コンセプトSUV", "SAIC MG", "未来モビリティ", "東洋美学"],
        tags_ko: ["컨셉 SUV", "SAIC MG", "미래 모빌리티", "동양미학"],
        tags_ar: ["SUV مفاهيمي", "SAIC MG", "تنقل المستقبل", "جماليات شرقية"],
        tags_de: ["Konzept-SUV", "SAIC MG", "Zukunftsmobilität", "Östliche Ästhetik"],
        tags_fr: ["SUV Concept", "SAIC MG", "Mobilité Future", "Esthétique Orientale"],
        detail: "上汽名爵MG寻星概念SUV项目，以「寻星」为主题，将东方美学中对星空的浪漫想象融入SUV造型设计。车身线条兼具力量感与优雅，前脸设计灵感来自星辰轨迹，内饰强调科技与人文的平衡。",
        detail_en: "SAIC MG Xunxing Concept SUV, themed 'Seeking Stars', integrating the romantic imagination of starry skies in Eastern aesthetics into SUV design. The body lines combine power and elegance, with front face design inspired by stellar trajectories, and interior emphasizing the balance between technology and humanity.",
        detail_ja: "SAIC MG XunxingコンセプトSUV。「寻星」をテーマに、東洋美学の星空への浪漫的想像をSUVデザインに融合。ボディラインは力強さと優雅さを兼ね備え、フロントフェイスのデザインは星の軌跡からインスピレーションを得て、インテリアはテクノロジーと人文のバランスを強調。",
        detail_ko: "SAIC MG Xunxing 컨셉 SUV. '寻星(별을 찾다)'을 주제로, 동양미학의 별하늘에 대한 낭만적 상상을 SUV 디자인에 융합. 바디 라인은 힘과 우아함을 겸비하고, 프론트 페이스 디자인은 별의 궤적에서 영감을 얻었으며, 인테리어는 기술과 인문의 균형을 강조.",
        detail_ar: "SAIC MG Xunxing SUV المفاهيمي، بموضوع \"البحث عن النجوم\"، يدمج الخيال الرومانسي للسماء المرصعة بالنجوم في الجماليات الشرقية في تصميم SUV. تجمع خطوط الجسم بين القوة والأناقة، مع تصميم الواجهة الأمامية مستوحى من مسارات النجوم، والداخلية تؤكد على التوازن بين التكنولوجيا والإنسانية.",
        detail_de: "SAIC MG Xunxing Konzept-SUV, mit dem Thema 'Sterne Suchen', integriert die romantische Vorstellung vom Sternenhimmel in der östlichen Ästhetik in das SUV-Design. Die Karosserielinien vereinen Kraft und Eleganz, das Frontdesign inspiriert von Sternbahnen, und das Interieur betont die Balance zwischen Technologie und Humanität.",
        detail_fr: "SAIC MG Xunxing SUV Concept, sur le thème « À la recherche des étoiles », intégrant l'imagination romantique du ciel étoilé dans l'esthétique orientale dans le design SUV. Les lignes de carrosserie allient puissance et élégance, le design facial avant inspiré des trajectoires stellaires, et l'intérieur soulignant l'équilibre entre technologie et humanité."
    },
    {
        year: "26",
        title: "悍马 · 荒雅 — <span>越野概念设计</span>",
        title_en: "HUMMER · Huangya — <span>Off-Road Concept Design</span>",
        title_ja: "ハマー · 荒雅 — <span>オフロードコンセプトデザイン</span>",
        title_ko: "허머 · 황아 — <span>오프로드 컨셉 디자인</span>",
        title_ar: "هامر · هوانغيا — <span>تصميم الطرق الوعرة المفاهيمي</span>",
        title_de: "HUMMER · Huangya — <span>Offroad-Konzeptdesign</span>",
        title_fr: "HUMMER · Huangya — <span>Design Concept Tout-Terrain</span>",
        desc: "荒野不是绝望之地，而是盛宴之所——将战士精神注入现代越野车设计，融合粗犷力量与东方雅致美学。",
        desc_en: "The wilderness is not a place of despair but a feast — injecting warrior spirit into modern off-road vehicle design, blending rugged power with Eastern elegant aesthetics.",
        desc_ja: "荒野は絶望の地ではなく宴の場——戦士の精神を現代オフロードデザインに注ぎ、粗犷な力と東洋の雅やかな美学を融合。",
        desc_ko: "황야는 절망의 땅이 아닌 연회의 장소 — 전사의 정신을 현대 오프로드 디자인에 주입하여 거친 힘과 동양의 우아한 미학을 융합.",
        desc_ar: "البرية ليست مكان يأس بل مأدبة — حقن روح المحارب في تصميم سيارات الطرق الوعرة الحديثة، مزج القوة الغليظة بالجماليات الشرقية الأنيقة.",
        desc_de: "Die Wildnis ist kein Ort der Verzweiflung, sondern ein Fest — Kriegergeist wird in modernes Offroad-Design injiziert, das robuste Kraft mit östlicher eleganter Ästhetik verbindet.",
        desc_fr: "La nature sauvage n'est pas un lieu de désespoir mais un festin — injection de l'esprit guerrier dans le design tout-terrain moderne, alliant puissance brute et esthétique élégante orientale.",
        tags: ["越野车", "悍马", "概念设计", "东方美学"],
        tags_en: ["Off-Road Vehicle", "HUMMER", "Concept Design", "Eastern Aesthetics"],
        tags_ja: ["オフロード車", "ハマー", "コンセプトデザイン", "東洋美学"],
        tags_ko: ["오프로드 차량", "허머", "컨셉 디자인", "동양미학"],
        tags_ar: ["سيارة طرق وعرة", "هامر", "تصميم مفاهيمي", "جماليات شرقية"],
        tags_de: ["Offroad-Fahrzeug", "HUMMER", "Konzeptdesign", "Östliche Ästhetik"],
        tags_fr: ["Tout-Terrain", "HUMMER", "Design Concept", "Esthétique Orientale"],
        detail: "悍马·荒雅设计项目将悍马品牌标志性的硬派越野基因与东方「荒雅」美学理念相融合。「荒」代表荒野的原始力量与不羁精神，「雅」则是东方文化中的精致与克制。设计在保持悍马强悍越野性能的同时，注入了东方美学中对自然与力量关系的独特理解，创造出兼具野性与优雅的新一代越野概念车。",
        detail_en: "The HUMMER · Huangya design project fuses HUMMER's iconic rugged off-road DNA with the Eastern aesthetic philosophy of 'Huangya' (Wild Elegance). 'Huang' represents the primal power and untamed spirit of the wilderness, while 'Ya' embodies the refinement and restraint in Eastern culture. The design maintains HUMMER's formidable off-road capabilities while injecting Eastern aesthetic understanding of the relationship between nature and power, creating a new generation off-road concept that balances wildness and elegance.",
        detail_ja: "ハマー・荒雅デザインプロジェクトは、ハマーの象徴的なタフなオフロードDNAと東洋の「荒雅」美学理念を融合。「荒」は荒野の原始的な力と不羈の精神を表し、「雅」は東洋文化の精緻さと抑制を体現。ハマーの強力なオフロード性能を維持しつつ、自然と力の関係に対する東洋美学の独自の理解を注ぎ込み、野性と優雅さを兼ね備えた新世代オフロードコンセプトを創造。",
        detail_ko: "허머·황아 디자인 프로젝트는 허머의 상징적인 거친 오프로드 DNA와 동양의 '황아(荒雅)' 미학 이념을 융합. '황(荒)'은 황야의 원시적 힘과 불굴의 정신을 나타내고, '아(雅)'는 동양 문화의 정교함과 절제를 체현. 허머의 강력한 오프로드 성능을 유지하면서 자연과 힘의 관계에 대한 동양 미학의 독특한 이해를 주입하여 야성과 우아함을 겸비한 차세대 오프로드 컨셉을 창조.",
        detail_ar: "يمزج مشروع تصميم هامر · هوانغيا بين الحمض النووي الرمزي الوعر لعلامة هامر وفلسفة الجماليات الشرقية \"هوانغيا\" (الأناقة البرية). يمثل \"هوانغ\" القوة البدائية والروح الجامحة للبرية، بينما يجسد \"يا\" الرقي والضبط في الثقافة الشرقية. يحافظ التصميم على قدرات هامر الوعرة الهائلة مع حقن الفهم الجمالي الشرقي الفريد لعلاقة الطبيعة والقوة، مما يخلق جيلاً جديداً من المفاهيم الوعرة التي توازن بين البرية والأناقة.",
        detail_de: "Das HUMMER · Huangya Designprojekt verschmilzt HUMMERs ikonische robuste Offroad-DNA mit der östlichen Ästhetikphilosophie von 'Huangya' (Wilde Eleganz). 'Huang' repräsentiert die urtümliche Kraft und den ungezähmten Geist der Wildnis, während 'Ya' die Raffinesse und Zurückhaltung in der östlichen Kultur verkörpert. Das Design behält HUMMERs formidable Offroad-Fähigkeiten bei und injiziert das östliche ästhetische Verständnis der Beziehung zwischen Natur und Kraft, wodurch ein neuer Offroad-Konzept entsteht, das Wildheit und Eleganz in Balance bringt.",
        detail_fr: "Le projet de design HUMMER · Huangya fusionne l'ADN tout-terrain robuste iconique de HUMMER avec la philosophie esthétique orientale du « Huangya » (Élégance Sauvage). « Huang » représente la force primitive et l'esprit indompté de la nature sauvage, tandis que « Ya » incarne le raffinement et la retenue dans la culture orientale. Le design maintient les formidables capacités tout-terrain de HUMMER tout en injectant la compréhension esthétique orientale unique de la relation entre nature et pouvoir, créant un nouveau concept tout-terrain équilibrant sauvagerie et élégance."
    },
    {
        year: "26",
        title: "Alfa Romeo Otto Vittoria 33 — <span>经典致敬概念超跑</span>",
        title_en: "Alfa Romeo Otto Vittoria 33 — <span>Classic Tribute Concept Supercar</span>",
        title_ja: "Alfa Romeo Otto Vittoria 33 — <span>クラシックオマージュコンセプトスーパーカー</span>",
        title_ko: "Alfa Romeo Otto Vittoria 33 — <span>클래식 경의 컨셉 슈퍼카</span>",
        title_ar: "Alfa Romeo Otto Vittoria 33 — <span>سيارة خارقة مفاهيمية تكريماً للكلاسيكية</span>",
        title_de: "Alfa Romeo Otto Vittoria 33 — <span>Klassisches Hommage-Konzept-Supercar</span>",
        title_fr: "Alfa Romeo Otto Vittoria 33 — <span>Supercar Concept Hommage Classique</span>",
        desc: "致敬经典赛车的限量概念超跑，传承 Vittorio Jano 的黄金时代设计灵魂，融合意大利赛车传统与当代设计语言。",
        desc_en: "A limited-edition concept supercar paying tribute to classic racing, inheriting the design soul of Vittorio Jano's golden era, blending Italian racing tradition with contemporary design language.",
        desc_ja: "クラシックレーシングに敬意を表する限定コンセプトスーパーカー。ヴィットリオ・ヤーノの黄金時代のデザイン魂を継承し、イタリアのレーシング伝統と現代のデザイン言語を融合。",
        desc_ko: "클래식 레이싱에 경의를 표하는 한정판 컨셉 슈퍼카. 비토리오 야노의 황금시대 디자인 영혼을 계승하고, 이탈리아 레이싱 전통과 현대 디자인 언어를 융합.",
        desc_ar: "سيارة خارقة مفاهيمية محدودة الإصدار تكريماً للسباقات الكلاسيكية، ترث روح تصميم العصر الذهبي لفيتوريو جانو، وتمزج بين تقليد السباق الإيطالي ولغة التصميم المعاصرة.",
        desc_de: "Ein limitiertes Konzept-Supercar als Hommage an den klassischen Rennsport, das die Designseele der goldenen Ära von Vittorio Jano erbt und italienische Renntradition mit zeitgenössischer Designsprache verbindet.",
        desc_fr: "Un supercar concept en édition limitée rendant hommage à la course classique, héritant de l'âme du design de l'âge d'or de Vittorio Jano, mêlant tradition de course italienne et langage de design contemporain.",
        tags: ["超级跑车", "Alfa Romeo", "经典致敬", "赛车传统"],
        tags_en: ["Supercar", "Alfa Romeo", "Classic Tribute", "Racing Heritage"],
        tags_ja: ["スーパーカー", "Alfa Romeo", "クラシックオマージュ", "レーシングヘリテージ"],
        tags_ko: ["슈퍼카", "Alfa Romeo", "클래식 경의", "레이싱 헤리티지"],
        tags_ar: ["سيارة خارقة", "Alfa Romeo", "تكريم كلاسيكي", "تراث السباقات"],
        tags_de: ["Supercar", "Alfa Romeo", "Klassische Hommage", "Rennsport-Erbe"],
        tags_fr: ["Supercar", "Alfa Romeo", "Hommage Classique", "Héritage de Course"],
        detail: "Alfa Romeo Otto Vittoria 33 是一款向品牌辉煌赛车历史致敬的限量概念超跑。设计灵感源自 Vittorio Jano 主导的黄金时代——那个 Alfa Romeo 在赛道上叱咤风云的年代。项目将经典赛车的纯粹线条与空气动力学效率，和现代超级跑车的科技前沿相结合，创造出既怀旧又前瞻的设计语言。「Otto Vittoria」意为「八次胜利」，致敬 Alfa Romeo 在 F1 历史上的八次世界冠军荣耀。",
        detail_en: "Alfa Romeo Otto Vittoria 33 is a limited-edition concept supercar paying homage to the brand's glorious racing history. Design inspiration draws from the golden era led by Vittorio Jano — when Alfa Romeo dominated the tracks. The project combines the pure lines and aerodynamic efficiency of classic racing cars with the technological frontier of modern supercars, creating a design language that is both nostalgic and forward-looking. 'Otto Vittoria' means 'Eight Victories', honoring Alfa Romeo's eight World Championship titles in F1 history.",
        detail_ja: "Alfa Romeo Otto Vittoria 33は、ブランドの輝かしいレーシング歴史にオマージュを捧げる限定コンセプトスーパーカー。ヴィットリオ・ヤーノが主導した黄金時代——Alfa Romeoがトラックを支配した時代からデザインのインスピレーションを得ている。クラシックレーシングカーの純粋なラインと空力効率を、現代スーパカーの技術的最前線と組み合わせ、懐かしさと先見性を兼ね備えたデザイン言語を創造。「Otto Vittoria」は「8つの勝利」を意味し、F1歴史におけるAlfa Romeoの8回のワールドチャンピオンシップの栄光を称える。",
        detail_ko: "Alfa Romeo Otto Vittoria 33은 브랜드의 빛나는 레이싱 역사에 경의를 표하는 한정판 컨셉 슈퍼카. 비토리오 야노가 주도한 황금시대 — Alfa Romeo가 트랙을 지배하던 시절에서 디자인 영감을 얻었다. 클래식 레이싱카의 순수한 라인과 공기역학적 효율성을 현대 슈퍼카의 기술 최전선과 결합하여 향수과 선견성을 겸비한 디자인 언어를 창조. 'Otto Vittoria'는 '8번의 승리'를 의미하며, F1 역사에서 Alfa Romeo의 8회 월드 챔피언십 영광을 기린다.",
        detail_ar: "Alfa Romeo Otto Vittoria 33 هي سيارة خارقة مفاهيمية محدودة الإصدار تكريماً لتاريخ السباقات المجيد للعلامة التجارية. يستلهم التصميم من العصر الذهبي الذي قاده فيتوريو جانو — عندما هيمنت Alfa Romeo على الحلبات. يجمع المشروع بين الخطوط النقية والكفاءة الديناميكية الهوائية لسيارات السباق الكلاسيكية مع الحد التكنولوجي لسيارات السوبركار الحديثة، مما يخلق لغة تصميم تجمع بين الحنين والنظرة المستقبلية. تعني \"Otto Vittoria\" \"ثمانية انتصارات\"، تكريماً لثمانية ألقاب بطولة عالمية لـ Alfa Romeo في تاريخ F1.",
        detail_de: "Alfa Romeo Otto Vittoria 33 ist ein limitiertes Konzept-Supercar als Hommage an die glorreiche Rennsportgeschichte der Marke. Design-Inspiration stammt aus der von Vittorio Jano geführten goldenen Ära — als Alfa Romeo die Strecken dominierte. Das Projekt kombiniert die reinen Linien und aerodynamische Effizienz klassischer Rennwagen mit der technologischen Spitze moderner Supercars und schafft eine Designprache, die sowohl nostalgisch als auch zukunftsorientiert ist. 'Otto Vittoria' bedeutet 'Acht Siege' und ehrt Alfa Romeos acht Weltmeistertitel in der F1-Geschichte.",
        detail_fr: "L'Alfa Romeo Otto Vittoria 33 est un supercar concept en édition limitée rendant hommage à la glorieuse histoire de course de la marque. L'inspiration du design provient de l'âge d'or mené par Vittorio Jano — quand Alfa Romeo dominait les circuits. Le projet combine les lignes pures et l'efficacité aérodynamique des voitures de course classiques avec la pointe technologique des supercars modernes, créant un langage de design à la fois nostalgique et prospectif. « Otto Vittoria » signifie « Huit Victoires », en hommage aux huit titres de Championnat du Monde d'Alfa Romeo dans l'histoire de la F1."
    }
];

// ==================== FITNESS ====================
var FITNESS = {
    p1: "以<strong>器械训练</strong>和<strong>有氧运动</strong>为主，兼顾柔韧与体能提升。相信设计中的比例感与结构思维，同样适用于对身体的雕刻。",
    p1_en: "Focused on <strong>strength training</strong> and <strong>cardio</strong>, balancing flexibility and conditioning. The proportion and structural thinking from design applies equally to sculpting the body.",
    p1_ja: "<strong>筋力トレーニング</strong>と<strong>有酸素運動</strong>を中心に、柔軟性と体力向上も兼顾。デザインにおける比例感と構造思考は、身体の造形にもそのまま適用できると信じています。",
    p1_ko: "<strong>근력 운동</strong>과 <strong>유산소 운동</strong>을 중심으로, 유연성과 체력 향상도 겸비. 디자인의 비례감과 구조적 사고는 신체 조각에도 그대로 적용된다고 믿는다.",
    p1_ar: "يركز على <strong>تدريب القوة</strong> و<strong>التمارين الهوائية</strong>، مع مراعاة المرونة واللياقة. الإحساس بالتناسب والتفكير الهيكلي في التصميم ينطبقان أيضاً على نحت الجسم.",
    p1_de: "Fokus auf <strong>Krafttraining</strong> und <strong>Cardio</strong>, mit Flexibilität und Konditionierung. Das Proportionsgefühl und strukturelle Denken aus dem Design lässt sich ebenso auf die Körpergestaltung anwenden.",
    p1_fr: "Axé sur la <strong>musculation</strong> et le <strong>cardio</strong>, équilibrant flexibilité et conditionnement. Le sens des proportions et la pensée structurelle du design s'appliquent également à la sculpture du corps.",
    p2: "训练理念：<strong>循序渐进</strong>，<strong>科学量化</strong>，追求长期主义的身体投资。设计审美与健身追求，共享同一种对「美」的定义。",
    p2_en: "Philosophy: <strong>progressive overload</strong>, <strong>scientific quantification</strong>, long-term investment in the body. Design aesthetics and fitness share the same definition of 'beauty'.",
    p2_ja: "トレーニング哲学：<strong>漸進的過負荷</strong>、<strong>科学的定量化</strong>、長期主義の身体への投資。デザイン美学とフィットネスの追求は、「美」に対する同じ定義を共有しています。",
    p2_ko: "훈련 철학: <strong>점진적 과부하</strong>, <strong>과학적 정량화</strong>, 장기주의의 신체 투자. 디자인 미학과 피트니스 추구는 '아름다움'에 대한 같은 정의를 공유한다.",
    p2_ar: "الفلسفة: <strong>التحميل التدريجي</strong>، <strong>التحديد العلمي</strong>، استثمار طويل الأمد في الجسم. جماليات التصميم واللياقة تشتركان في نفس تعريف \"الجمال\".",
    p2_de: "Philosophie: <strong>progressive Überlastung</strong>, <strong>wissenschaftliche Quantifizierung</strong>, langfristige Investition in den Körper. Designästhetik und Fitness teilen dieselbe Definition von \"Schönheit\".",
    p2_fr: "Philosophie : <strong>surcharge progressive</strong>, <strong>quantification scientifique</strong>, investissement à long terme dans le corps. L'esthétique du design et le fitness partagent la même définition de la « beauté ».",
    tracks: [
        {
            title: "器械训练",
            title_en: "Strength Training",
            title_ja: "ウェイトトレーニング",
            title_ko: "기구 운동",
            title_ar: "تدريب القوة",
            title_de: "Krafttraining",
            title_fr: "Musculation",
            desc: "杠铃 · 哑铃 · 固定器械 — 肌肉力量的系统化雕塑",
            desc_en: "Barbell · Dumbbell · Machines — Systematic sculpting of muscular strength",
            desc_ja: "バーベル · ダンベル · マシン — 筋肉力の体系的な彫刻",
            desc_ko: "바벨 · 덤벨 · 머신 — 근육력의 체계적 조각",
            desc_ar: "باربل · دمبل · آلات — النحت المنهجي للقوة العضلية",
            desc_de: "Langhantel · Kurzhantel · Maschinen — Systematische Gestaltung der Muskelkraft",
            desc_fr: "Barre · Haltère · Machines — Sculpture systématique de la force musculaire",
            image: ""
        },
        {
            title: "有氧运动",
            title_en: "Cardio",
            title_ja: "有酸素運動",
            title_ko: "유산소 운동",
            title_ar: "تمارين هوائية",
            title_de: "Cardio",
            title_fr: "Cardio",
            desc: "跑步 · 单车 · 划船机 — 心肺功能的持续强化",
            desc_en: "Running · Cycling · Rowing — Continuous enhancement of cardiovascular fitness",
            desc_ja: "ランニング · サイクリング · ボート — 心肺機能の継続的強化",
            desc_ko: "러닝 · 사이클링 · 로잉 — 심폐기능의 지속적 강화",
            desc_ar: "جري · دراجة · تجديف — تعزيز مستمر للياقة القلب والأوعية الدموية",
            desc_de: "Laufen · Radfahren · Rudern — Kontinuierliche Stärkung der Herz-Kreislauf-Fitness",
            desc_fr: "Course · Vélo · Aviron — Renforcement continu de la condition cardiovasculaire",
            image: ""
        },
        {
            title: "体能训练",
            title_en: "Conditioning",
            title_ja: "コンディショニング",
            title_ko: "체력 단련",
            title_ar: "اللياقة البدنية",
            title_de: "Konditionstraining",
            title_fr: "Conditionnement",
            desc: "HIIT · 功能性训练 — 全面提升身体素质",
            desc_en: "HIIT · Functional Training — Comprehensive fitness improvement",
            desc_ja: "HIIT · ファンクショナルトレーニング — 総合的な体力向上",
            desc_ko: "HIIT · 기능성 훈련 — 종합적 체력 향상",
            desc_ar: "HIIT · تدريب وظيفي — تحسين شامل للياقة البدنية",
            desc_de: "HIIT · Funktionelles Training — Umfassende Fitnessverbesserung",
            desc_fr: "HIIT · Entraînement fonctionnel — Amélioration complète de la condition physique",
            image: ""
        },
        {
            title: "柔韧与恢复",
            title_en: "Flexibility & Recovery",
            title_ja: "柔軟性 & リカバリー",
            title_ko: "유연성 & 회복",
            title_ar: "المرونة والتعافي",
            title_de: "Flexibilität & Regeneration",
            title_fr: "Flexibilité & Récupération",
            desc: "拉伸 · 筋膜放松 — 运动表现的保障",
            desc_en: "Stretching · Foam Rolling — Essential for performance",
            desc_ja: "ストレッチ · フォームローリング — パフォーマンスの保障",
            desc_ko: "스트레칭 · 폼롤링 — 수행 능력의 보장",
            desc_ar: "تمدد · لف الرغوة — ضمان الأداء الرياضي",
            desc_de: "Dehnen · Faszienrolle — Essential für die Leistung",
            desc_fr: "Étirements · Foam Rolling — Essentiel pour la performance",
            image: ""
        },
        {
            title: "训练风格",
            title_en: "Training Style",
            title_ja: "トレーニングスタイル",
            title_ko: "훈련 스타일",
            title_ar: "أسلوب التدريب",
            title_de: "Trainingsstil",
            title_fr: "Style d'Entraînement",
            desc: "渐进超负荷 · 科学量化 · 长期主义",
            desc_en: "Progressive Overload · Scientific · Long-term",
            desc_ja: "漸進的過負荷 · 科学的定量化 · 長期主義",
            desc_ko: "점진적 과부하 · 과학적 정량화 · 장기주의",
            desc_ar: "التحميل التدريجي · العلمي · طويل الأمد",
            desc_de: "Progressive Überlastung · Wissenschaftlich · Langfristig",
            desc_fr: "Surcharge Progressive · Scientifique · Long terme",
            image: ""
        }
    ]
};
